"""Make worker_id nullable

Revision ID: 99e2ae42c786
Revises: 8c5e37e286a6
Create Date: 2025-08-22 15:53:07.850897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e2ae42c786'
down_revision = '8c5e37e286a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column(
            'worker_id',
            existing_type=sa.INTEGER(),
            nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column(
            'worker_id',
            existing_type=sa.INTEGER(),
            nullable=False
        )

    # ### end Alembic commands ###
